### ISSUE TITLE
Cnchi [0.14.204] - does not create seperate /home partition

### ISSUE THREAD

**Issue by killajoe** [Antergos/Cnchi#690] opened 2017-01-12 17:16 UTC
### Problem:
*Cnchi [0.14.204] - does not create seperate /home partition if choosen*

### Steps To Reproduce:
1. starting the live iso [antergos-17.1-x86_64.iso]

2. waiting for cnchi to update

3. following the installer  till you are on "how you like to proceed?" choose "set your home in a different partition/volume"

4.  proceed with the installer till summery and controling Partititions summary, you will see no extra Partition for home neither there is an option to choose a partition or volume.

### Log Files
- Link to [/tmp/cnchi.log](http://paste2.org/e7mG24J9) output. 
- Link to [/tmp/postinstall.log](http://paste2.org/VZWYGdNp).

### Additional Notes:

see here: https://forum.antergos.com/topic/5857/new-installation-with-latest-iso-antergos-17-1-x86_64-iso-issues

**Comment by karasu** [comment] 2017-01-16 17:23
```
2017-01-10 14:45:40 [INFO] ask.py(430) store_values(): Antergos will be installed using a separate /home partition.
2017-01-10 14:45:40 [DEBUG] automatic.py(155) populate_devices(): ATA Hitachi HDS72105 [500 GB] (/dev/sda)
2017-01-10 14:45:40 [DEBUG] automatic.py(155) populate_devices(): ATA Intenso SSD Sat [120 GB] (/dev/sdb)
2017-01-10 14:45:40 [DEBUG] automatic.py(155) populate_devices(): ATA WDC WD1600AAJS-7 [160 GB] (/dev/sdc)
2017-01-10 14:45:40 [DEBUG] automatic.py(155) populate_devices():   [15 GB] (/dev/sdd)
2017-01-10 14:45:59 [INFO] automatic.py(340) set_bootloader(): Antergos wird den Bootloader grub2 auf Gerät ‚/dev/sdb‘ installieren
2017-01-10 14:45:59 [DEBUG] auto_partition.py(386) get_devices(): /dev/sdb
2017-01-10 14:45:59 [DEBUG] auto_partition.py(386) get_devices(): /dev/sdb
2017-01-10 14:45:59 [DEBUG] auto_partition.py(469) get_mount_devices(): /dev/sdb3 assigned to be mounted in /home
2017-01-10 14:45:59 [DEBUG] auto_partition.py(469) get_mount_devices(): /dev/sdb1 assigned to be mounted in /boot
2017-01-10 14:45:59 [DEBUG] auto_partition.py(469) get_mount_devices(): /dev/sdb2 assigned to be mounted in /
2017-01-10 14:45:59 [DEBUG] auto_partition.py(469) get_mount_devices(): /dev/sdb5 assigned to be mounted in swap
2017-01-10 14:45:59 [DEBUG] auto_partition.py(386) get_devices(): /dev/sdb
2017-01-10 14:45:59 [DEBUG] auto_partition.py(509) get_fs_devices(): Device /dev/sdb1 will have a ext4 filesystem
2017-01-10 14:45:59 [DEBUG] auto_partition.py(509) get_fs_devices(): Device /dev/sdb5 will have a swap filesystem
2017-01-10 14:45:59 [DEBUG] auto_partition.py(509) get_fs_devices(): Device /dev/sdb3 will have a ext4 filesystem
2017-01-10 14:45:59 [DEBUG] auto_partition.py(509) get_fs_devices(): Device /dev/sdb2 will have a ext4 filesystem
2017-01-10 14:46:12 [DEBUG] automatic.py(155) populate_devices(): ATA Hitachi HDS72105 [500 GB] (/dev/sda)
2017-01-10 14:46:12 [DEBUG] automatic.py(155) populate_devices(): ATA Intenso SSD Sat [120 GB] (/dev/sdb)
2017-01-10 14:46:12 [DEBUG] automatic.py(155) populate_devices(): ATA WDC WD1600AAJS-7 [160 GB] (/dev/sdc)
2017-01-10 14:46:12 [DEBUG] automatic.py(155) populate_devices():   [15 GB] (/dev/sdd)
2017-01-10 14:47:45 [DEBUG] run_cmd.py(104) call(): /dev/sdc1: LABEL="windows" UUID="60AC29E0AC29B208" TYPE="ntfs" PARTUUID="3f1c28f5-01"
2017-01-10 14:48:24 [INFO] advanced.py(1721) on_partition_list_new_label_activate(): Creating a new msdos partition table for disk /dev/sda
2017-01-10 14:48:25 [DEBUG] run_cmd.py(104) call(): /dev/sdc1: LABEL="windows" UUID="60AC29E0AC29B208" TYPE="ntfs" PARTUUID="3f1c28f5-01"
2017-01-10 14:48:57 [DEBUG] advanced.py(1237) on_partition_list_new_activate(): Creating a primary partition
2017-01-10 14:48:58 [WARNING] fs_module.py(104) get_type(): Error running ['blkid', '-o', 'value', '-s', 'TYPE', '/dev/sda1']: b''
2017-01-10 14:48:59 [DEBUG] run_cmd.py(104) call(): /dev/sdc1: LABEL="windows" UUID="60AC29E0AC29B208" TYPE="ntfs" PARTUUID="3f1c28f5-01"
2017-01-10 14:49:09 [INFO] advanced.py(1721) on_partition_list_new_label_activate(): Creating a new msdos partition table for disk /dev/sdb
2017-01-10 14:49:09 [WARNING] fs_module.py(104) get_type(): Error running ['blkid', '-o', 'value', '-s', 'TYPE', '/dev/sda1']: b''
2017-01-10 14:49:09 [DEBUG] run_cmd.py(104) call(): /dev/sdc1: LABEL="windows" UUID="60AC29E0AC29B208" TYPE="ntfs" PARTUUID="3f1c28f5-01"
2017-01-10 14:49:41 [DEBUG] advanced.py(1237) on_partition_list_new_activate(): Creating a primary partition
2017-01-10 14:49:42 [WARNING] fs_module.py(104) get_type(): Error running ['blkid', '-o', 'value', '-s', 'TYPE', '/dev/sda1']: b''
2017-01-10 14:49:42 [WARNING] fs_module.py(104) get_type(): Error running ['blkid', '-o', 'value', '-s', 'TYPE', '/dev/sdb1']: b''
2017-01-10 14:49:42 [DEBUG] run_cmd.py(104) call(): /dev/sdc1: LABEL="windows" UUID="60AC29E0AC29B208" TYPE="ntfs" PARTUUID="3f1c28f5-01"
2017-01-10 14:49:55 [DEBUG] advanced.py(1237) on_partition_list_new_activate(): Creating a primary partition
2017-01-10 14:49:56 [WARNING] fs_module.py(104) get_type(): Error running ['blkid', '-o', 'value', '-s', 'TYPE', '/dev/sda1']: b''
2017-01-10 14:49:56 [WARNING] fs_module.py(104) get_type(): Error running ['blkid', '-o', 'value', '-s', 'TYPE', '/dev/sdb2']: b''
2017-01-10 14:49:56 [WARNING] fs_module.py(104) get_type(): Error running ['blkid', '-o', 'value', '-s', 'TYPE', '/dev/sdb1']: b''
2017-01-10 14:49:56 [DEBUG] run_cmd.py(104) call(): /dev/sdc1: LABEL="windows" UUID="60AC29E0AC29B208" TYPE="ntfs" PARTUUID="3f1c28f5-01"
2017-01-10 14:50:18 [INFO] advanced.py(2162) set_bootloader(): Antergos will install the bootloader grub2 in device /dev/sdb
2017-01-10 14:50:18 [DEBUG] advanced.py(2115) get_changes(): Device /dev/sdb1 will be created, relabeled, formatted, mounted as swap and not encrypted.
2017-01-10 14:50:18 [DEBUG] advanced.py(2115) get_changes(): Device /dev/sdb2 will be created, relabeled, formatted, mounted as / and not encrypted.
2017-01-10 14:50:18 [DEBUG] advanced.py(2115) get_changes(): Device /dev/sda1 will be created, relabeled, formatted, mounted as /home and not encrypted.```

**Comment by karasu** [comment] 2017-01-16 17:29
@killajoe you first tried "automatic" installation using /dev/sdb
```
/dev/sdb3 assigned to be mounted in /home
/dev/sdb1 assigned to be mounted in /boot
/dev/sdb2 assigned to be mounted in /
/dev/sdb5 assigned to be mounted in swap
```
but then, you choose advanced one, with a different setup:
``` 
Device /dev/sdb1 will be created, relabeled, formatted, mounted as swap and not encrypted.
Device /dev/sdb2 will be created, relabeled, formatted, mounted as / and not encrypted.
Device /dev/sda1 will be created, relabeled, formatted, mounted as /home and not encrypted.```
```
Am I right?
What was your original intention?

**Comment by karasu** [comment] 2017-01-16 17:49
@killajoe by the way, can you run blkid in your computer? As this (as root):
```
blkid -o value -s TYPE /dev/sda1
```
Thanks!

**Comment by killajoe** [comment] 2017-01-16 17:52
First i try to use automatic partition and enable/mark "set your home in a different partition/volume" because i need to have home on /dev/sda.
When i reach the overview i see that there is no option to choose different place for /home and i go back inside cnchi to partition by hand/manual.

____
/dev/sda1 is ext4 ;)

**Comment by karasu** [comment] 2017-01-16 17:57
Ah! In automatic, there is no option to choose which partition you want to be your /home. Everything is automatic. It uses the whole device as it pleases. It's for novice users.

If you want more control you have to choose advanced, as you did.

So, no need to fix anything here, as it works as intended 👍 

There's this other error, though:

```
2017-01-10 14:48:58 [WARNING] fs_module.py(104) get_type(): Error running ['blkid', '-o', 'value', '-s', 'TYPE', '/dev/sda1']: b''
``` 
This is an old error that I can't reproduce here. It seems that, in some circumstances, `blkid` does not return the correct partition type ¿? That's why I was asking you to run blkid, to see if it works or not. Does it run correctly when you type `blkid` in your terminal?

**Comment by killajoe** [comment] 2017-01-16 18:04
yes blkid gives me ext4 as answear.

CNCHI shows the partition value like this:
http://kamprad.net/wp-content/uploads/2016/11/cnchi-10.png
It looks like it is an option for automatic erase disk.
Should be then under the "choose exactly" section as an option...

**Comment by karasu** [comment] 2017-01-16 18:12
Nope, I didn't make myself clear. When you choose automatic, you can, as an option, tell cnchi to setup your harddisk in a way that / and /home are in separate partitions (volumes if you choose LVM).

The "choose exactly" allows you to create/format partitions and choose where to mount them as you please.

The blkid thingie will remain a mistery.... 😞 

If you don't mind, I'll close this. Thanks!

**Closed by karasu** 2017-01-16 18:12 UTC
Labels: needs confirmation, needs testing
