### ISSUE TITLE
Metalinks error

### ISSUE THREAD

**Issue by tkdberger** [Antergos/Cnchi#783] opened 2017-08-10 14:15 UTC
### Problem:
When I reach the "Create your user account" screen, an error message appear, shown at http://imgur.com/rGYDtF0 The number It instructs me to reference is `15361`.

### Steps To Reproduce:
1. Run Cnchi
2. Reach "Create your user account" screen
3. Observe error
4. ~~Cry~~

### Log Files
- [`/tmp/cnchi.log`](https://paste2.org/EgFhbJze)
- `/tmp/postinstall.log` does not exist.

### Additional Notes:

`sudo pacman -Syu` gives the error `error: failed to update antergos (invalid or corrupted database (PGP signature))` (**only** for the `antergos` database/repository.)

**Comment by karasu** [comment] 2017-08-10 18:30
Hi,

The problem is here:
```
2017-08-10 09:46:50 [ERROR] pac.py(557) cb_log(): could not open file /var/lib/pacman/sync/antergos.db: Unrecognized archive format
```
This can be one of these things:
- Bad downloaded ISO / bad burned ISO (did you check your downloaded iso md5?)
- Bad antergos.db download (simply try it again).
- Bad antergos mirror (faulty mirror).

If you checked your downloaded iso and are sure that is burned correctly (to dvd or usb), it's nearly sure that it was a mirror problem. It could even solve it itself by just retrying after some hours. If the problem persist, you can force cnchi to not sort the mirror list this way:
- Run antergos iso live.
- Wait for cnchi to update itself.
- When it reopens itself, close it.
- Open a terminal and run cnchi this way: `sudo -E cnchi -dv --disable-rank-mirrors`

More info: https://forum.antergos.com/topic/3267/how-to-choose-your-mirrors-before-installing-antergos

**Closed** 2017-08-10 22:23 UTC

**Comment by tkdberger** [comment] 2017-08-12 14:50
(It was a bad image. Note to self, use a better writer next time.)
