### ISSUE TITLE
Installation error KDE : qt5-styleplugins is missing

### ISSUE THREAD

**Issue by Wertos** [Antergos/Cnchi#1139] opened 2019-03-26 17:48 UTC
**Describe the bug**
Installation failed with error: Cannot find these package qt5-styleplugins.
In step: Checking that all selected packages are available online...

**Comment by leonardlorenz** [comment] 2019-03-26 19:28
I'll hop on on this issue, I have the same problem.

here's an image of the error  
https://imgur.com/a/eZel4t4

Here's a log file:  
https://leonardlorenz.de/log.txt

**Comment by trevligttrevande** [comment] 2019-03-26 20:01
I have the same problem.

It is obviously caused by this problem:
https://github.com/Antergos/antergos-packages/issues/450

**Comment by Scanner320085** [comment] 2019-03-27 15:59
I have the same problem.

qt5-styleplugins always appear in [Antergos/Cnchi/blob/master/data/packages.xml](https://github.com/Antergos/Cnchi/blob/master/data/packages.xml)
![image](https://user-images.githubusercontent.com/48996602/55091689-9aea7180-50b1-11e9-83fe-5a8b414043bb.png)

**Comment by Wertos** [comment] 2019-03-27 18:03
I deleted the line from the file data.xml with this package, did not help.

**Comment by 2308662212** [comment] 2019-03-30 02:22
Same problem here. However, if you choose to install with the base system. This error would not show up.

**Comment by karasu** [comment] 2019-03-31 06:38
Fixed by removing a dependency. Also package is in arch community repository again (and in antergos repository, just in case).

**Closed by karasu** 2019-03-31 06:38 UTC
