### ISSUE TITLE
Installer hangs at "Copying xz files from cache..."

### ISSUE THREAD

**Issue by Jevans101** [Antergos/Cnchi#264] opened 2015-02-15 15:49 UTC
Hi.
I've been trying to install Antergos today but it seems the installer is preventing me from doing so.  The installer hangs   at "Copying xz files from cache..." .  I've noticed a few others have been having the same problem on the Google Plus community page and on the forums.  Around the time the installer crashes, I get the message: "[pac.py] ERROR: unresolvable package conflicts detected" in cnchi.log.  I hope this issue can be resolved soon, this is my favorite Linux distribution.
![screenshot from 2015-02-15 15 41 38](https://cloud.githubusercontent.com/assets/6298400/6203753/29f7e96c-b529-11e4-99fb-4650f4ede812.png)

**Comment by chris062689** [comment] 2015-02-15 19:42
Duplicate of #263.  Proposed solution.

**Closed** 2015-02-15 21:30 UTC
Labels: duplicate
