### ISSUE TITLE
no internet connection bug

### ISSUE THREAD

**Issue by sudoaza** [Antergos/Cnchi#353] opened 2015-05-29 01:06 UTC
on has_connection at cnchi/misc/misc.py +886 the ip didn't work, tryed google dns and also didn't work. finally replaced it by http://somestaticsite.com and it showed me as connected and let me install. 

Being that this distro aims to be accesible for newbie users the installer should work :P 

Using antergos-2015.04.12-x86_64.torrent

**Comment by Mikaela** [comment] 2015-05-29 06:23
Duplicate of https://github.com/Antergos/Cnchi/issues/303 which is fixed, but Cnchi is not updating automatically for some reason.

> Being that this distro aims to be accesible for newbie users the installer should work :P

Wrong, the *for anyone* is misleading and more accurate is said to be *for anyone who is committed to Arch*.

**Comment by sudoaza** [comment] 2015-05-29 06:38
ok, sorry

**Closed** 2015-05-29 06:45 UTC
Labels: duplicate
