### ISSUE TITLE
Can't install because installer says cnchi is not up to date

### ISSUE THREAD

**Issue by theSoenke** [Antergos/Cnchi#462] opened 2015-11-11 19:57 UTC
The latest cnchi version was downloaded and installed automatically, but the installer still says my version is not up to date and i can't continue

![screenshot from 2015-11-11 20-52-46](https://cloud.githubusercontent.com/assets/1757301/11101318/9b1dcaf6-88b6-11e5-9218-e9cfced71033.png)

**Comment by karasu** [comment] 2015-11-11 21:18
@theSoenke : I updated the stable version just today. Latest version is 0.12.36. Let me check that it has been updated by our build server (@lots0logs knows better than me how this works).

**Comment by karasu** [comment] 2015-11-11 21:22
Duplicate of issue #461

**Comment by lots0logs** [comment] 2015-11-11 21:37
It should be okay now. Cheers!

**Comment by karasu** [comment] 2015-11-11 21:43
@lots0logs : I still see 0.12.34 Am I missing something?

**Comment by AaronTakizad** [comment] 2015-11-12 03:58
For now, here's what worked for me. In terminal, run:
`
sudo pacman -S --force cnchi-dev
`

**Comment by karasu** [comment] 2015-11-18 17:57
There was a problem with the package update in our build server, already solved by @lots0logs . Next time remember that Cnchi has the -n option, that bypasses all check restrictions.

**Closed by karasu** 2015-11-18 17:57 UTC
Labels: bug, critical

**Comment by boogiebangtrain** [comment] 2015-11-21 04:26
The issue has returned...

**Comment by boogiebangtrain** [comment] 2015-11-21 04:31
-n option worked however...?

**Comment by g33kSuperstar** [comment] 2015-11-21 04:54
Yes, so far... I had installed several VMs with Antergos in the last months, but the last release is just not working, after the system is installed it does not boot, it gets stuck in a black screen and now this error with cnchi... Hope this time will work with -n option, cause I really love Antergos!

**Comment by danger89** [comment] 2015-11-30 16:41
It's closed? But when I download the latest ISO I still suffer from this issue..

**Comment by karasu** [comment] 2015-11-30 17:03
@danger89 : Exactly, which version of Cnchi are you using?

You can avoid all tests with `sudo -E cnchi -dvn`

**Comment by danger89** [comment] 2015-12-02 18:04
@karasu I already installed it. So it's hard to say which version it was. However, because I was connected to the Internet. Cnchi updated itself. 
When Cnchi restart itselfs, to run the latest version. But somehow the icon doesn't get updated. It's not blocking, because I still could press the 'next' button.

**Comment by theSoenke** [comment] 2015-12-29 17:09
Still does not work in Cnchi 0.12.46. Only when starting with -n option is a installation possible
