### ISSUE TITLE
[Feature request] Option to install without internet

### ISSUE THREAD

**Issue by faridosc** [Antergos/Cnchi#313] opened 2015-04-24 18:12 UTC
It would be great if we could have the option to install system from usb/dvd without the installer downloading all the packages from the internet. 

this is very helpful in situations where you are in rural communities or places with slow internet connection.

**Comment by lots0logs** [comment] 2015-04-24 18:16
This is a duplicate of #286

**Closed by lots0logs** 2015-04-24 18:16 UTC
Labels: duplicate
