### ISSUE TITLE
Error: 161932 - Cnchi cannot install necessary packages

### ISSUE THREAD

**Issue by derhornspieler** [Antergos/Cnchi#822] opened 2017-11-28 00:09 UTC
### Problem:
Have reproduced Installation Error multiple times.  Please see Screenshot
<img width="1343" alt="screen shot 2017-11-27 at 7 08 34 pm" src="https://user-images.githubusercontent.com/15236687/33295907-6867b8fa-d3a6-11e7-97b8-8aa03444f63f.png">

### Steps To Reproduce:
1. Install Antergos as a VM on VMWare Fusion (Latest Build)
2. Select KDE and standard options for US.
3. Error occurs

### Log Files
- Use a service like http://paste2.org/ to provide links to the logs.
- Link to /tmp/cnchi.log output.
- Link to /tmp/postinstall.log.

**Comment by karasu** [comment] 2017-11-28 06:50
Please, can you post your log files, too?

**Comment by derhornspieler** [comment] 2017-11-28 17:25
Which logs do you need?  I will rerun it tonight and pull logs then.

Sent from my iPhone

On Nov 28, 2017, at 01:50, Gustau Castells <notifications@github.com<mailto:notifications@github.com>> wrote:


Please, can you post your log files, too?

**Comment by karasu** [comment] 2017-11-29 06:51
When the install fails, check the /tmp folder. There should be a cnchi.log file there.

It will be easier if you post it in paste2.org or a similar service and then put the link here.

Thanks!

**Comment by ntfs1984** [comment] 2017-11-29 16:58
Issue confirmed. But I have error: 0.
It can be reproduced with any DE choice. I tested with Mate and XFCE.

Anyway:

```
2017-11-29 16:38:13 [ERROR] pac.py(164) finalize_transaction(): Can't finalize alpm transaction: transaction failed, pm_errno 49 (conflicting files), [('intel-ucode', '/install/boot/intel-ucode.img', None), ('grub2-theme-antergos', '/install/boot/grub/themes/Antergos-Default/antergoslogo.png', None), ('grub2-theme-antergos', '/install/boot/grub/themes/Antergos-Default/ascii.pf2', None), ('grub2-theme-antergos', '/install/boot/grub/themes/Antergos-Default/background.png', None), ('grub2-theme-antergos', '/install/boot/grub/themes/Antergos-Default/icons/antergos.png', None), ('grub2-theme-antergos', '/install/boot/grub/themes/Antergos-Default/icons/debian.png', None), ('grub2-theme-antergos', '/install/boot/grub/themes/Antergos-Default/icons/fedora.png', None), ('grub2-theme-antergos', '/install/boot/grub/themes/Antergos-Default/icons/gentoo.png', None), ('grub2-theme-antergos', '/install/boot/grub/themes/Antergos-Default/icons/kubuntu.png', None), ('grub2-theme-antergos', '/install/boot/grub/themes/Antergos-Default/icons/linuxmint.png', None), ('grub2-theme-antergos', '/install/boot/grub/themes/Antergos-Default/icons/macosx.png', None), ('grub2-theme-antergos', '/install/boot/grub/themes/Antergos-Default/icons/opensuse.png', None), ('grub2-theme-antergos', '/install/boot/grub/themes/Antergos-Default/icons/recovery.png', None), ('grub2-theme-antergos', '/install/boot/grub/themes/Antergos-Default/icons/sabayon.png', None), ('grub2-theme-antergos', '/install/boot/grub/themes/Antergos-Default/icons/ubuntu.png', None), ('grub2-theme-antergos', '/install/boot/grub/themes/Antergos-Default/icons/windows.png', None), ('grub2-theme-antergos', '/install/boot/grub/themes/Antergos-Default/install.sh', None), ('grub2-theme-antergos', '/install/boot/grub/themes/Antergos-Default/rlwy14.pf2', None), ('grub2-theme-antergos', '/install/boot/grub/themes/Antergos-Default/rlwy16.pf2', None), ('grub2-theme-antergos', '/install/boot/grub/themes/Antergos-Default/select_c.png', None), ('grub2-theme-antergos', '/install/boot/grub/themes/Antergos-Default/slider_c.png', None), ('grub2-theme-antergos', '/install/boot/grub/themes/Antergos-Default/slider_n.png', None), ('grub2-theme-antergos', '/install/boot/grub/themes/Antergos-Default/slider_s.png', None), ('grub2-theme-antergos', '/install/boot/grub/themes/Antergos-Default/terminal_box_c.png', None), ('grub2-theme-antergos', '/install/boot/grub/themes/Antergos-Default/terminal_box_e.png', None), ('grub2-theme-antergos', '/install/boot/grub/themes/Antergos-Default/terminal_box_n.png', None), ('grub2-theme-antergos', '/install/boot/grub/themes/Antergos-Default/terminal_box_ne.png', None), ('grub2-theme-antergos', '/install/boot/grub/themes/Antergos-Default/terminal_box_nw.png', None), ('grub2-theme-antergos', '/install/boot/grub/themes/Antergos-Default/terminal_box_s.png', None), ('grub2-theme-antergos', '/install/boot/grub/themes/Antergos-Default/terminal_box_se.png', None), ('grub2-theme-antergos', '/install/boot/grub/themes/Antergos-Default/terminal_box_sw.png', None), ('grub2-theme-antergos', '/install/boot/grub/themes/Antergos-Default/terminal_box_w.png', None), ('grub2-theme-antergos', '/install/boot/grub/themes/Antergos-Default/theme.txt', None)]
2017-11-29 16:38:13 [DEBUG] pac.py(167) finalize_transaction(): Releasing alpm transaction...
2017-11-29 16:38:13 [DEBUG] pac.py(169) finalize_transaction(): Alpm transaction done.
2017-11-29 16:38:13 [INFO] slides.py(276) manage_events_from_cb_queue(): Updating antergos database
2017-11-29 16:38:13 [INFO] slides.py(276) manage_events_from_cb_queue(): Updating core database
2017-11-29 16:38:14 [DEBUG] pac.py(284) install(): REPO DB ORDER IS: [<alpm.DB object at 0x7fea80c20168>, <alpm.DB object at 0x7fea80c20078>, <alpm.DB object at 0x7fea80c20060>, <alpm.DB object at 0x7fea80c201e0>, <alpm.DB object at 0x7fea80c20150>]
2017-11-29 16:38:14 [INFO] slides.py(276) manage_events_from_cb_queue(): Updating extra database
2017-11-29 16:38:14 [INFO] slides.py(276) manage_events_from_cb_queue(): Updating community database
2017-11-29 16:38:14 [INFO] slides.py(276) manage_events_from_cb_queue(): Updating multilib database
2017-11-29 16:38:15 [DEBUG] pac.py(319) install(): ['automake', 'logrotate', 'fakeroot', 'gawk', 'usbutils', 'shadow', 'libtool', 'iputils', 'binutils', 'alsa-utils', 'os-prober', 'gettext', 'unrar', 'glibc', 'patch', 'bind-tools', 'sed', 'bison', 'flex', 'bash', 'less', 'exfat-utils', 'efibootmgr', 'coreutils', 'grub2-theme-antergos', 'acpid', 'systemd', 'antergos-mirrorlist', 'zd1211-firmware', 'mdadm', 'bzip2', 'tar', 'dosfstools', 'gzip', 'linux', 'reiserfsprogs', 'f2fs-tools', 'procps-ng', 'm4', 'autoconf', 'btrfs-progs', 'reflector', 'pciutils', 'wpa_actiond', 'inetutils', 'haveged', 'usb_modeswitch', 'sudo', 'antergos-desktop-settings', 'cifs-utils', 'net-tools', 'wireless_tools', 'lvm2', 'filesystem', 'wget', 'cryptsetup', 'pcmciautils', 'vi', 'jfsutils', 's-nail', 'git', 'grep', 'unzip', 'pulseaudio-bluetooth', 'openssh', 'dmraid', 'dhcpcd', 'make', 'man-pages', 'util-linux', 'bash-completion', 'sysfsutils', 'antergos-midnight-timers', 'texinfo', 'diffutils', 'ipw2100-fw', 'gcc-libs', 'pkgfile', 'ntfs-3g', 'terminus-font', 'blueberry', 'grub', 'whois', 'ipw2200-fw', 'networkmanager', 'psmisc', 'antergos-keyring', 'nfs-utils', 'systemd-sysvcompat', 'perl', 'licenses', 'mlocate', 'bluez', 'nano', 'antergos-common-meta', 'device-mapper', 'file', 'gcc', 'e2fsprogs', 'bzr', 'findutils', 'modemmanager', 'cmake', 'antergos-mate-meta', 'groff', 'bluez-utils', 'crda', 'nilfs-utils', 'netctl', 'which', 'pacman', 'man-db', 'intel-ucode', 'iproute2', 'yaourt', 'b43-fwcutter', 'pkg-config', 'xfsprogs']
2017-11-29 16:38:15 [DEBUG] pac.py(326) install(): 118 target(s) found
2017-11-29 16:38:15 [DEBUG] pac.py(157) finalize_transaction(): Prepare alpm transaction...
2017-11-29 16:38:16 [DEBUG] pac.py(572) cb_log(): dependency cycle detected:
2017-11-29 16:38:16 [DEBUG] pac.py(572) cb_log(): harfbuzz will be installed before its freetype2 dependency
2017-11-29 16:38:16 [DEBUG] pac.py(572) cb_log(): dependency cycle detected:
2017-11-29 16:38:16 [DEBUG] pac.py(572) cb_log(): libglvnd will be installed before its mesa dependency
2017-11-29 16:38:16 [DEBUG] pac.py(572) cb_log(): dependency cycle detected:
2017-11-29 16:38:16 [DEBUG] pac.py(572) cb_log(): usbmuxd will be installed before its libimobiledevice dependency
2017-11-29 16:38:16 [DEBUG] pac.py(159) finalize_transaction(): Commit alpm transaction...
2017-11-29 16:38:16 [INFO] slides.py(276) manage_events_from_cb_queue(): Resolving dependencies...
2017-11-29 16:38:16 [INFO] slides.py(276) manage_events_from_cb_queue(): Checking inter conflicts...
2017-11-29 16:38:16 [INFO] slides.py(276) manage_events_from_cb_queue(): Checking keys in keyring...
2017-11-29 16:38:16 [INFO] slides.py(276) manage_events_from_cb_queue(): Checking integrity...
2017-11-29 16:38:19 [INFO] slides.py(276) manage_events_from_cb_queue(): Loading packages...
2017-11-29 16:38:23 [INFO] slides.py(276) manage_events_from_cb_queue(): Checking file conflicts...
2017-11-29 16:38:24 [ERROR] pac.py(164) finalize_transaction(): Can't finalize alpm transaction: transaction failed, pm_errno 49 (conflicting files), [('intel-ucode', '/install/boot/intel-ucode.img', None), ('grub2-theme-antergos', '/install/boot/grub/themes/Antergos-Default/antergoslogo.png', None), ('grub2-theme-antergos', '/install/boot/grub/themes/Antergos-Default/ascii.pf2', None), ('grub2-theme-antergos', '/install/boot/grub/themes/Antergos-Default/background.png', None), ('grub2-theme-antergos', '/install/boot/grub/themes/Antergos-Default/icons/antergos.png', None), ('grub2-theme-antergos', '/install/boot/grub/themes/Antergos-Default/icons/debian.png', None), ('grub2-theme-antergos', '/install/boot/grub/themes/Antergos-Default/icons/fedora.png', None), ('grub2-theme-antergos', '/install/boot/grub/themes/Antergos-Default/icons/gentoo.png', None), ('grub2-theme-antergos', '/install/boot/grub/themes/Antergos-Default/icons/kubuntu.png', None), ('grub2-theme-antergos', '/install/boot/grub/themes/Antergos-Default/icons/linuxmint.png', None), ('grub2-theme-antergos', '/install/boot/grub/themes/Antergos-Default/icons/macosx.png', None), ('grub2-theme-antergos', '/install/boot/grub/themes/Antergos-Default/icons/opensuse.png', None), ('grub2-theme-antergos', '/install/boot/grub/themes/Antergos-Default/icons/recovery.png', None), ('grub2-theme-antergos', '/install/boot/grub/themes/Antergos-Default/icons/sabayon.png', None), ('grub2-theme-antergos', '/install/boot/grub/themes/Antergos-Default/icons/ubuntu.png', None), ('grub2-theme-antergos', '/install/boot/grub/themes/Antergos-Default/icons/windows.png', None), ('grub2-theme-antergos', '/install/boot/grub/themes/Antergos-Default/install.sh', None), ('grub2-theme-antergos', '/install/boot/grub/themes/Antergos-Default/rlwy14.pf2', None), ('grub2-theme-antergos', '/install/boot/grub/themes/Antergos-Default/rlwy16.pf2', None), ('grub2-theme-antergos', '/install/boot/grub/themes/Antergos-Default/select_c.png', None), ('grub2-theme-antergos', '/install/boot/grub/themes/Antergos-Default/slider_c.png', None), ('grub2-theme-antergos', '/install/boot/grub/themes/Antergos-Default/slider_n.png', None), ('grub2-theme-antergos', '/install/boot/grub/themes/Antergos-Default/slider_s.png', None), ('grub2-theme-antergos', '/install/boot/grub/themes/Antergos-Default/terminal_box_c.png', None), ('grub2-theme-antergos', '/install/boot/grub/themes/Antergos-Default/terminal_box_e.png', None), ('grub2-theme-antergos', '/install/boot/grub/themes/Antergos-Default/terminal_box_n.png', None), ('grub2-theme-antergos', '/install/boot/grub/themes/Antergos-Default/terminal_box_ne.png', None), ('grub2-theme-antergos', '/install/boot/grub/themes/Antergos-Default/terminal_box_nw.png', None), ('grub2-theme-antergos', '/install/boot/grub/themes/Antergos-Default/terminal_box_s.png', None), ('grub2-theme-antergos', '/install/boot/grub/themes/Antergos-Default/terminal_box_se.png', None), ('grub2-theme-antergos', '/install/boot/grub/themes/Antergos-Default/terminal_box_sw.png', None), ('grub2-theme-antergos', '/install/boot/grub/themes/Antergos-Default/terminal_box_w.png', None), ('grub2-theme-antergos', '/install/boot/grub/themes/Antergos-Default/theme.txt', None)]
2017-11-29 16:38:24 [DEBUG] pac.py(167) finalize_transaction(): Releasing alpm transaction...
2017-11-29 16:38:24 [DEBUG] pac.py(169) finalize_transaction(): Alpm transaction done.
2017-11-29 16:38:24 [ERROR] process.py(130) run(): "Can't install necessary packages. Cnchi can't continue."
2017-11-29 16:38:24 [ERROR] process.py(135) run(): Traceback (most recent call last):
2017-11-29 16:38:24 [ERROR] process.py(135) run():   File "/usr/share/cnchi/src/installation/process.py", line 108, in run
    self.pkg.packages, self.down.metalinks)
2017-11-29 16:38:24 [ERROR] process.py(135) run():   File "/usr/share/cnchi/src/pages/advanced.py", line 2451, in run_install
    self.installation.start()
2017-11-29 16:38:24 [ERROR] process.py(135) run():   File "/usr/share/cnchi/src/misc/extra.py", line 192, in helper
    return func(*args, **kwargs)
2017-11-29 16:38:24 [ERROR] process.py(135) run():   File "/usr/share/cnchi/src/installation/install.py", line 318, in start
    self.install_packages()
2017-11-29 16:38:24 [ERROR] process.py(135) run():   File "/usr/share/cnchi/src/installation/install.py", line 529, in install_packages
    raise InstallError(txt)
2017-11-29 16:38:24 [ERROR] process.py(135) run(): misc.extra.InstallError: "Can't install necessary packages. Cnchi can't continue."
```

**Comment by derhornspieler** [comment] 2017-11-29 23:05
New Error: 164271

Log File Cnchi.log:  https://paste2.org/y54k3w3z <https://paste2.org/y54k3w3z>

Best,

James R.

**Comment by ntfs1984** [comment] 2017-11-29 23:39
Guys, please pay attention on this issue, because of it, Antergos can't be installed at all.

**Comment by karasu** [comment] 2017-11-30 07:26
I see two different issues here:
@ntfs1984 : 
Your issue is that you have already a failed installation in your system. There is no problem with / as it gets formatted each time, but your /boot does not. This means that there are already some files in your system so alpm (pacman library) refuses to install intel-ucode and grub2-theme-antergos packages. I'll issue a new Cnchi release with a fix for this case asap.

@derhornspieler Your issue most of the time is either caused by a faulty package or a faulty mirror. Let me do some tests.

**Comment by ntfs1984** [comment] 2017-11-30 14:23
@karasu 

Tried new installation a hour ago, still not working.

But yes, you're right, there is some conflict with another files in dedicated /boot partition (I'm using few Linuxes on my PC). Used single partition for / and /boot, and everything works fine.

**Thank you for efforts!**

**Comment by mimecry** [comment] 2018-06-21 09:45
issue has resurfaced, i haven't able to install antergos the past few days. also getting error 0 like @ntfs1984 did. 

i tried multiple USBs, both the live and minimal ISOs, and even tried them on metal as well as Virtualbox. same error appears at the end of the installation every time without fail

**Comment by karasu** [comment] 2018-06-21 09:50
@mimecry some users are experiencing issues with some mirrors. We're investigating it. Meanwhile you can sort your mirrors in the mirrors screen, or even better, sort them before running the installer.
Remove the mirror `http://repo.antergos.info/antergos/x86_64/` if you have it in your `/etc/pacman.d/antergos-mirrorlist` file.

More info: https://forum.antergos.com/topic/10140/antergos-installer-crashes-at-the-end/22?page=3

**Comment by mimecry** [comment] 2018-06-21 10:03
gotcha, thanks for the info. as a sidenote i have only been trying KDE installations exclusively, let me test some other DEs and report back

**Comment by killajoe** [comment] 2018-06-22 18:08
@mimecry kde fails cause by a checksum error on a package itself (liblastfm-qt5), needs to be solved at the buildserver, but this one is a sleep at the moment, will be solved soon...

**Comment by mimecry** [comment] 2018-06-23 14:40
@killajoe yes i had just caught up with the info at the Antergos forum. nothing to do but wait for now then

**Comment by mimecry** [comment] 2018-06-25 09:37
tried again today after reading the latest post in the forum thread, no success yet. still patiently waiting 😃

**Comment by mimecry** [comment] 2018-06-26 11:14
KDE installs fine again! (with cnchi auto-sorted mirrors). thanks to all involved in fixing these bugs.

**Closed** 2018-07-23 07:48 UTC
