### ISSUE TITLE
Cannot create download package list (metalinks)

### ISSUE THREAD

**Issue by MysterialPy** [Antergos/Cnchi#771] opened 2017-06-30 09:43 UTC
### Problem:
Error: 669367
Cnchi runs into an error while installing...

I have tried updating with `pacman -Sy cnchi`. Same error.
(GNOME, KDE, Cinnamon) - Same Errors

### Steps To Reproduce:
1. Boot Latest Antergos Live USB
2. Update cnchi
3. Run an Install

### Log Files
cnchi.log - https://paste2.org/D71t8893
pacman-boot.log - https://paste2.org/HmnLY4pU

### Additional Notes:

cnchi update - https://paste2.org/eIt0f18g

**Comment by jkw** [comment] 2017-06-30 21:51
A fix has already been applied to this issue.
https://github.com/Antergos/antergos-packages/commit/5c9a89e8b94d16eff4b7b90b182920e110c2e4e6

Duplicate of #770

**Comment by stratus-ss** [comment] 2017-07-05 16:59
Closing as duplicate as @jwk mentions

**Closed by stratus-ss** 2017-07-05 16:59 UTC

**Comment by jkw** [comment] 2017-07-05 17:03
@jkw ;-)

Den ons 5 juli 2017 18:59stratus-ss <notifications@github.com> skrev:

**Comment by marcolondonuk** [comment] 2018-01-20 15:23
Today is 20th of January 2018 and I have decided after many years of using ubuntu distribution to make the change and switch to antergos (looks much more professionally built than ubuntu). I successfully burned a CD with antergos iso file on it and run the installation procedure including I opted for wiping out my 120gb ssd etc. I set up country, keyboard, etc all run smoothly until I got the error message: 'cannot create download package list (metalinks).' Please reference the following number when reporting this error: 235504. Can anyone help me to overcome this error? Many thanks, marco

**Comment by killajoe** [comment] 2018-01-20 21:21
@marcolondonuk you should open a new bug, as the nature of rolling releases your issue is not the same...
