### ISSUE TITLE
Replace xf86-input-synaptics with xf86-input-libinput (at least in gnome)

### ISSUE THREAD

**Issue by Noxbru** [Antergos/Cnchi#681] opened 2016-12-16 21:06 UTC
2 problems:
- According to Arch, xf86-input-synaptics is in maintenance mode, and xf86-input-libinput should be prefered: https://git.archlinux.org/svntogit/packages.git/tree/trunk/xf86-input-synaptics.install?h=packages/xf86-input-synaptics#n3
- Gnome, since version 3.20 doesn't work with xf86-input-synaptics (in the sense that the changes you make in the configuration doesn't actually take place)

Solution, change xf86-input-synaptics by xf86-input-libinput.

**Comment by slacka** [comment] 2016-12-18 07:25
This is basically a dupe of https://github.com/Antergos/antergos-iso/issues/65

**Closed** 2016-12-18 07:42 UTC
Labels: duplicate

**Comment by Noxbru** [comment] 2016-12-18 09:50
It's true that this is a duplicate of Antergos/antergos-iso#65. But I think that this is a more correct place to discuss the issue.

Now, I still think that something should be done. Antergos Gnome users would expect that the configuration tool for the mouse/touchpad work.

**Comment by slacka** [comment] 2016-12-18 20:00
@Noxbru 
Please see the discussion on Antergos/antergos-iso#65. There is a trade-off between missing features and broken hardware and a broken GUI tweak tool. The devs have decided to hold off a bit as they see the former as more serious than the latter.
