### ISSUE TITLE
TypeError in installation/advanced.py:657

### ISSUE THREAD

**Issue by lots0logs** [Antergos/Cnchi#409] opened 2015-09-07 17:10 UTC
## Exception in Cnchi

**TypeError** in **installation/advanced.py:657**
argument of type &#x27;NoneType&#x27; is not iterable

[View on Bugsnag](https://bugsnag.com/antergos/cnchi/errors/55ed37e80f76499ec4646e5e?event_id=55ed37f3d69bfb1435d0aab7)

## Stacktrace

    installation/advanced.py:657 - fill_partition_list
    installation/advanced.py:842 - update_view
    installation/advanced.py:1527 - prepare
    main_window.py:412 - on_forward_button_clicked

[View full stacktrace](https://bugsnag.com/antergos/cnchi/errors/55ed37e80f76499ec4646e5e?event_id=55ed37f3d69bfb1435d0aab7)

**Comment by karasu** [comment] 2015-09-07 20:39
Fixed in 0.13.8 (I can't test it because I can't reproduce it, it just occurs when a filesystem can't be detected)

**Closed by karasu** 2015-09-07 20:39 UTC
Labels: 0.12.1, bugsnag
