### ISSUE TITLE
In minimal installation, /home/USERNAME/.config is owned by root

### ISSUE THREAD

**Issue by Kirek** [Antergos/Cnchi#301] opened 2015-04-19 19:51 UTC
Just this, very weird things happen when applications cannot use this directory :)
The only file there is ~/.config/fontconfig/fonts.conf

**Comment by mattchewie** [comment] 2015-04-23 05:13
I have experienced the same when I did a full KDE install. This caused several errors to be thrown on first boot.

Just out of curiosity, did you do a UEFI install with Gummiboot?

**Comment by mattchewie** [comment] 2015-04-23 05:27
My GNOME install just finished. I can confirm that the .config in my home directory is correctly owned by the "user". So this looks like it might be an issue tied to non-gnome installs? I will try a XFCE install in a VM tomorrow to see if I get the same outcome as the KDE install.

**Comment by karasu** [comment] 2015-04-23 06:45
@lots0logs : If I understand correctly, this is a minimal ISO issue, isn't it? Also KDE installation seems to be affected by this.

**Comment by mattchewie** [comment] 2015-04-23 14:18
FYI : XFCE install also as the correct permissions

**Comment by axaxs** [comment] 2015-05-11 01:01
This has been fixed in dev, not sure on policy on closing/commenting/testing so just leaving a comment here.

**Comment by lots0logs** [comment] 2015-05-11 03:07
We need to backport the fix into stable.

**Comment by erikdubois** [comment] 2015-05-14 14:09
i can confirm that as of today the bare installation STILL SUFFERS from the fact that .config is owned by ROOT. Users get error messages thrown by Spotify. Each time re-login. Variety wallpapers settings. Thunar Settings... etc. Any program that wants to write there, will sometimes give an error or just nothing but all your settings are not saved.

**Comment by karasu** [comment] 2015-05-18 08:31
@lots0logs : Has this been solved in stable?

**Comment by erikdubois** [comment] 2015-05-18 09:40
just tried the latest iso 20150516 this has still this issue!

**Comment by karasu** [comment] 2015-05-19 10:25
Fixed in postinstall.sh. Closing!

**Closed by karasu** 2015-05-19 10:25 UTC
Labels: bug
