### ISSUE TITLE
Keyboard layout detector

### ISSUE THREAD

**Issue by Wabuo** [Antergos/Cnchi#449] opened 2015-10-10 15:42 UTC
I would love if you culd implement an Ubuntu/Ubiquity alike keyboard layout detector.
The Ubiquity code doing this is on [launchpad.net](http://bazaar.launchpad.net/~ubuntu-installer/ubiquity/trunk/view/head:/ubiquity/keyboard_detector.py).

**Comment by karasu** [comment] 2015-10-10 16:13
Which keyboard layout are you using? It should detect it

**Comment by Wabuo** [comment] 2015-10-11 15:09
As you can see there https://github.com/Antergos/Cnchi/issues/423 non ... =)

If you use the Ubuntu installer it is the possibility to let the installer guess the keyboard so you don't have to know what kind of keyboard you use. The installer dos this by asking you to pres the shown keys or say that you don't have this key.

**Comment by karasu** [comment] 2015-10-11 17:36
#423 is a different issue.

Cnchi should autodetect your keymap. There's also an edit box for you to test.

![antergos-keymap](https://cloud.githubusercontent.com/assets/175797/10418011/649a0a00-704f-11e5-9685-76a0e06091e5.png)

**Comment by karasu** [comment] 2015-11-18 18:27
Closing as a duplicate of #423 (if @Wabuo disagrees we can reopen it).

**Closed by karasu** 2015-11-18 18:27 UTC

**Comment by Wabuo** [comment] 2015-11-27 20:40
I was talking about the detection of dead keys / no dead keys for example.
I prefer the Ubuntu way because it asked my to press a few requested keys and then it piked the right language, this way I knew that it was the right German and not one of the “thousands of others”.
