### ISSUE TITLE
Issue with Cnchi on the Antergos minimal iso

### ISSUE THREAD

**Issue by kkraku** [Antergos/Cnchi#530] opened 2016-02-07 17:33 UTC
Just asking if anyone else had an issue where they get to any screen mentioning partitioning and the top bar goes black and the UI glitches? I was still able to click the required settings from memory but it was really annoying. All the UI elements dissapeared. I am on 0.12.47 - the latest version shipped with the minimal iso which I downloaded this morning.

**Comment by lots0logs** [comment] 2016-02-07 18:44
Hi, could you try the minimal image that is in testing right now and let us know the result? Thanks!

https://build.antergos.com/browse/testing

**Comment by doeixd** [comment] 2016-02-11 16:04
I can confirm this. This just happened to me with that iso

**Comment by 0x587669** [comment] 2016-02-12 20:26
same here.

**Comment by pioutw** [comment] 2016-02-14 14:30
same for me too (cpu 32bit non-SSE2)

**Comment by enno09** [comment] 2016-02-20 13:22
The problem still exists with new antergos-minimal-2016.02.19-x86_64.iso
Tested on an asus n3150i-c mainboard with an intel celeron 3050 and integrated graphics.
The problem started with selecting the language.

**Comment by ikselven** [comment] 2016-03-03 15:12
Can confirm this issue with antergos-minimal-2016.02.21-x86_64.iso, trying to install via usb key on a uefi system.

**Comment by theSoenke** [comment] 2016-03-11 17:35
Same problem here with antergos-minimal-2016.02.21-x86_64.iso

**Comment by stratus-ss** [comment] 2017-01-10 16:09
@theSoenke @ikselven @enno09 I cannot reproduce this with the latest minimal iso, can you confirm if this issue is still present?

Thanks

**Comment by ikselven** [comment] 2017-01-22 23:02
Did a quick test installing Antergos in a virtual machine using antergos-minimal-17.1-x86_64.iso and everything worked fine. I cannot test it on real hardware though.

**Comment by kkraku** [comment] 2017-01-23 00:19
No longer have that hardware or an Antergos install. I'll try that ISO on a Lenovo Ideapad soon.

**Comment by stratus-ss** [comment] 2017-01-23 12:27
I also couldn't reproduce this. I am going to close this for now. We can reopen if it crops back up

**Closed by stratus-ss** 2017-01-23 12:27 UTC
Labels: bug
