### ISSUE TITLE
Gummiboot now 'systemd-boot/bootctl'

### ISSUE THREAD

**Issue by WokSearedBacon** [Antergos/Cnchi#427] opened 2015-09-20 15:27 UTC
Attempting to install a system with Gummiboot results in a fatal package not found error, given the Arch repositories have dropped the package. This is due to Gummiboot being merged into systemd.

CHANGELOG post: http://lists.freedesktop.org/archives/systemd-devel/2015-May/032147.html

To use the systemd version, much of what has to be done is changing 'gummiboot' to 'bootctl' in commands. Otherwise (such as in entry configuration, loader.conf) Gummiboot configurations will still work.

**Comment by karasu** [comment] 2015-09-20 15:38
Which version did you use? This has already been fixed in Cnchi 0.12.14

https://github.com/Antergos/Cnchi/commit/77fc043c31454c141754b6fe675b9b2975e0fa1d

Duplicate of:
https://github.com/Antergos/Cnchi/issues/402

**Comment by WokSearedBacon** [comment] 2015-09-20 15:39
0.12.12 Now I know!

**Closed** 2015-09-20 15:39 UTC
Labels: duplicate
