### ISSUE TITLE
Error: no such device.....

### ISSUE THREAD

**Issue by satriani-vai** [Antergos/Cnchi#532] opened 2016-02-08 14:40 UTC
```
Loading Linux core repo kernel...
Error: no such partition.
Loading initial ramdisk...
Error: you need to load the kernel first.

Press any key to continue...
```

ISO: antergos-2016.02.07-x86_64.iso
Commit: 19acc17

**Comment by stratus-ss** [comment] 2017-01-10 16:06
The commit has since been integrated. I cannot reproduce this. Closing due to age

**Closed by stratus-ss** 2017-01-10 16:06 UTC
