### ISSUE TITLE
'Cannot find these packages: xorg-mkfontdir': add_fatal in /usr/share/cnchi/src/misc/events.py:83

### ISSUE THREAD

**Issue by axb993** [Antergos/Cnchi#1127] opened 2019-03-07 05:04 UTC
Problem:
Cnchi fails to install as it cannot find the package 'xorg-mkfontdir'. Assuming this is because the package was renamed to xorg-mkfontscale today.

Steps To Reproduce:
1. Try to install with any options (or at least I can confirm it happens with all options set to default)
2. Cnchi will throw an error while checking for package availability.

Should be able to remedy this by referencing xorg-mkfontscale instead.

**Comment by zeratulmdq** [comment] 2019-03-07 12:45
Same issue over here. Thanks for taking it so fast @karasu :slightly_smiling_face:

**Comment by ekianjo** [comment] 2019-03-07 13:15
Same issue here, cannot proceed to installation because of this error...

**Comment by smaTc** [comment] 2019-03-07 16:07
Can also confirm.

**Comment by tbiancostuff** [comment] 2019-03-07 16:36
I can also confirm, I hope this will be fixed soon

**Comment by EDiLD** [comment] 2019-03-07 20:34
I can also confirm this.

**Comment by EDiLD** [comment] 2019-03-07 22:25
Workaround: https://forum.antergos.com/compose?p=/topic/11467/xorg-mkfontdir-breaks-installation-for-all-versions/4

**Comment by karasu** [comment] 2019-03-08 06:39
Fixed in antergos-common-meta package. It will take a bit to the mirrors to update. Meanwhile you can use the above workaround.

**Comment by arcbtc** [comment] 2019-03-09 11:29
Still not working here, and workaround also seems to not work. I delete the line with xorg-mkfontdir, do 'cnchi -p /usr/shar/cnchi/data/packages.xml', but it still throws same error?
'cannot find these packages: xorg-mkfontdir' add_fatal in /usr/share/cnchi/src/misc/events.py 83'

**Comment by arcbtc** [comment] 2019-03-09 11:48
My mistake, you have to run cnchi first before applying the workaround

**Comment by linlinlin1992** [comment] 2019-03-10 02:28
I would like to confirm the problem still persists without applying the workaround.

**Comment by killajoe** [comment] 2019-03-10 11:55
still not solved as i can see on testing it in a VM (EFI boot)

**Comment by Stele77** [comment] 2019-03-10 19:26
Wow, i was going MAD over this.. It still is not working, hope the workaround helps me, will report back..

**Comment by DanitiKain** [comment] 2019-03-11 20:26
Was still broke for me last night I will try when I get home to get this working.

**Comment by Beiri22** [comment] 2019-03-11 20:55
I cannot remember an Antergos install that worked out of the box. But I hope it gets fixed soon.

**Comment by DanitiKain** [comment] 2019-03-11 21:29
Yes and if I wasn' t so lazy I would install arch from scratch. I hate manjaro as well. Antergos has everything right except this install script. What is it gonna take to get it right.

**Comment by FingolinDetlef** [comment] 2019-03-12 15:03
Had the same issue yesterday, trying to install Antergos on my PC.

A month back or so it worked flawless on my Laptop, keep up the good work and thank you!

**Comment by daelvn** [comment] 2019-03-12 15:29
Had the same issue _right now_, so I can confirm. The workaround above worked, though

**Comment by killajoe** [comment] 2019-03-12 19:47
i was wondering why it do not work, as cnchi should read the file (packages.xml) directly from github, and the file on github is fixed:
https://github.com/Antergos/Cnchi/blob/0.16.x/data/packages.xml

**Comment by killajoe** [comment] 2019-03-12 20:47
https://github.com/Antergos/Cnchi/pull/1130

**Comment by lots0logs** [comment] 2019-03-12 22:51
https://github.com/Antergos/antergos-packages/issues/436#issuecomment-472211180

**Closed by lots0logs** 2019-03-12 22:51 UTC
Labels: bug, confirmed, needs testing
