### ISSUE TITLE
Error "can't create download package list"

### ISSUE THREAD

**Issue by sinayion** [Antergos/Cnchi#282] opened 2015-04-13 04:48 UTC
Cnchi version: 0.8.7-1
Iso: antergos-2015.04.12-x86_64
Region/locale: en-US

After the step with user details, I get the error: "can't create download package list". All optional checkboxes were selected (AUR, Firefox, etc.)

The log shows the following pac errors a few times:
 - "returning error 6 from alpm_db_get_pkg: wrong or NULL argument passed"
 - "returning error 6 from alpm_db_get_group: wrong or NULL argument passed"

Also:
 - "ERROR: Can't find these packages:   "
 - An error about creating a metalink for a package named " " (blank space)

**Comment by karasu** [comment] 2015-04-13 06:03
@sinayion , thanks for reporting.
What DE did you choose?
It looks like some package is missing. Maybe you got unlucky and you where using a non updated mirror
If you still have the log, copy it to a gist or pastebin and reference it here please.

**Comment by sinayion** [comment] 2015-04-13 06:10
- KDE4
I just noticed that if I install with only Bluetooth Support & Printing Support checked (the defaults), it works. Going to narrow it down to the offending group in a bit.

**Comment by sinayion** [comment] 2015-04-13 06:13
Argh, I need to head to bed. But it looks like it's one of:
 - Libreoffice
 - Firefox
 - Extra truetype fonts

**Comment by karasu** [comment] 2015-04-13 06:16
Don't worry @sinayion , narrowing to that is going to be very useful, thanks.

**Comment by jasuka** [comment] 2015-04-13 08:00
I have the same problem. I chose all packages except simple firewall. Cinnamon as desktop.

cnchi-dev log here: http://pastebin.com/bhZDbqgx

**Comment by jasuka** [comment] 2015-04-13 09:54
Did some testing and enabling LibreOffice causes the problem for me.

**Comment by karasu** [comment] 2015-04-13 09:55
Thanks. We'll look into it asap.

**Comment by roadev** [comment] 2015-04-13 17:26
Then, for KDE4 only the defaults? (only Bluetooth Support & Printing Support checked)

**Comment by karasu** [comment] 2015-04-13 17:33
Hi,

A wrong packages.xml file was being used by the installer. It should be ok now. I'll wait for your confirmation before closing this issue.

**Comment by karasu** [comment] 2015-04-13 17:35
Oh, and this is, in fact, a duplicate of issue #283

**Comment by Sqwrly** [comment] 2015-04-13 20:50
I'm trying to install on a T450S right now and I'm having this issue.

**Comment by karasu** [comment] 2015-04-13 20:53
Did you choose libreoffice? It's broken atm.

**Comment by Sqwrly** [comment] 2015-04-13 20:57
I did, but I took your comment of "It should be ok now." as it being fixed. :) I guess not.

**Comment by karasu** [comment] 2015-04-13 20:59
I'm afraid it is not...

El dilluns, 13 abril de 2015, Sqwrly <notifications@github.com> va escriure:

> I did, but I took your comment of "It should be ok now." as it being
> fixed. :) I guess not.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Antergos/Cnchi/issues/282#issuecomment-92496016>.
>


-- 
Enviat amb el meu Iphone

**Comment by lots0logs** [comment] 2015-04-14 10:39
FIxed with 51bb5b54239d54f15b033149a52f4bf3579c6c10

**Closed by lots0logs** 2015-04-14 10:39 UTC
Labels: bug, duplicate

**Comment by Tafhim** [comment] 2016-11-24 19:12
Just for anyone still facing this, this is now happening for the Flash plugin. I checked the log and unchecked the package on my subsequent try and it's working now.

**Comment by karasu** [comment] 2016-11-24 21:16
fixed by https://github.com/Antergos/Cnchi/commit/ce521832dfd137843f0b0bdd4f80c38070c69102

**Comment by SJOwl** [comment] 2017-01-27 06:31
I've faced up with the same problem when chose all packages. 
Then chose only Kernel, Printing Support, AUR, Chromium and Fonts.  
It's working now

**Comment by saterHATER** [comment] 2017-06-28 16:06
Broken in 0.14.72
Desktop: Gnome
Packages: none

This is potentially just network restrictions in my case.

**Comment by fgallaire** [comment] 2018-01-31 06:50
Same issue when selecting Deepin as desktop with Antergos 18.1

error 957276

2018-01-31 06:40:20 [ERROR] metalink.py(132) create(): Can't resolve these dependencies: deepin-artwork-themes
