### ISSUE TITLE
Cannot create download package list (metalinks)

### ISSUE THREAD

**Issue by locallycompact** [Antergos/Cnchi#845] opened 2018-01-21 15:31 UTC
### Problem:
Cnchi fails with the message 'Cannot create download package list (metalinks)'
Please reference the following number when reporting this error: 0

### Steps To Reproduce:
1. Just install

### Log Files
- https://paste2.org/6IHItnYc

**Comment by steevelefort** [comment] 2018-02-01 06:29
Same thing for me.
It works when installing Gnome but not if I try to install Deepin.

**Comment by sharpstringer** [comment] 2018-02-08 00:55
I've just had this exact issue.

**Comment by piegamesde** [comment] 2018-03-13 15:29
Same issue here. I managed to get around it by only using two mirrors, but it then failed during the installation. Apparently, some of your mirrors are broken.

**Comment by triinoxys** [comment] 2018-03-20 21:55
Same here, cannont install Antergos 18.3 (tested with all desktops).

**Comment by triinoxys** [comment] 2018-03-20 22:30
Had the same problem, just fixed it.
Problem is that some packages are missing (renamed, deleted, etc).

In our case (at this time), it's "inxi" package that got deleted.

Fix steps:
1. `wget https://raw.githubusercontent.com/Antergos/Cnchi/master/data/packages.xml`
2. `nano ~/packages.xml`
3. Remove line `<pkgname>inxi</pkgname>` and save
4. `sudo -E cnchi -dv -p ~/packages.xml`

Next time, missing package may have changed. To find out wich package is missing, run `cnchi` from terminal. When the error occurs, look for the package name (just before the error)

**Comment by karasu** [comment] 2018-03-20 22:54
Fixed by https://github.com/Antergos/Cnchi/commit/7023562e0c2722a1f7c651b35cf9e5e443a9da31

Thanks!

**Comment by antergostrying** [comment] 2018-04-26 19:35
Yesturday I was able to easily install Antergos; today with same ISO, same computer, same USB, same hard disk, I can't... 

It seems like Cnchi has multiple issues with missing packages: htop, python-gobject, modemmanager (I've tried 3 times by now, each one with a new ERROR).

Any ideas about how to fix this? Do I continue deleting lines from packages.xml?

**Comment by paddylernt** [comment] 2018-05-01 13:12
I am getting these "mirror failed", "package failed" and "cannot create package list" errors on AMD64 PC and Laptop. And it is the onlky network service that has a problem.

**Comment by paddylernt** [comment] 2018-05-10 21:37
Sorry about the long delay.
The current ISO uses Version 0.14.426 of Cnchi. I tried several variants of the install procedure (as root, as new user, different settings). But the result is always this: https://gist.github.com/paddylernt/bb1e07c23648c06ffca0e949984a3b99

**Comment by rjl6789** [comment] 2018-05-25 10:11
Hi - Same error as mentioned above, 0.14.426 when trying to install KDE
Same errors as paddylernt. I guess cnchi is broken and it's impossible to install? or is there a alternative installer package?

log below:
https://paste2.org/eCHAYOwE

**Comment by jose-sanchezm** [comment] 2018-05-25 12:15
Same error here trying to install Deepin. When selecting GNOME it completes the installation but fails with an integrity check leaving my computer in a unbootable state.

**Comment by karasu** [comment] 2018-05-25 12:19
I've detected that there is an error in the `antergos-desktop-settings` package. It's being rebuilt while I write these words. It will take time to reach all mirrors.

**Comment by karasu** [comment] 2018-05-25 12:21
@jose-sanchezm 
Your error is different:
`2018-05-25 10:01:30 [ERROR] pac.py(576) cb_log(): could not open file /var/lib/pacman/sync/antergos.db: Unrecognized archive format`
It seems the mirror you're using has a wrong version of the antergos.db database file.
When selecting mirrors, could you try to select the option of "not changing mirrorlist (default)" instead of "let cnchi sort your mirrorlists" ?

**Comment by austinv11** [comment] 2018-05-29 00:48
I'm having the same issue (albeit from a different cause).
`2018-05-29 00:43:35 [ERROR] metalink.py(132) create(): Can't resolve these dependencies: pacman<5.1 `
Log: https://gist.github.com/austinv11/6b433b666e01b9fd00039ba624157838

**Comment by CorruptComputer** [comment] 2018-05-29 02:16
This is happening to me as well, I cannot install however for me it says:
 ```
'Cannot create download package lists (metalinks).'
Please reference the following number when reporting this error: None
```
With this log in the terminal:
```
2018-05-29 02:08:42 [ERROR] metalink.py(132) create(): Can't resolve these dependencies: pacman<5.1 
2018-05-29 02:08:42 [ERROR] download.py(150) create_metalinks_list(): Error creating metalink for package antergos-gnome-meta. Installation will stop
2018-05-29 02:08:42 [ERROR] download.py(182) create_metalinks_list(): Can't create download set. An exception of type InstallError occured. Arguments:
('Error creating metalink for package antergos-gnome-meta. Installation will stop',)
2018-05-29 02:08:42 [ERROR] process.py(130) run(): 'Cannot create download package list (metalinks).'
2018-05-29 02:08:42 [ERROR] process.py(135) run(): Traceback (most recent call last):
2018-05-29 02:08:42 [ERROR] process.py(135) run():   File "/usr/share/cnchi/src/installation/process.py", line 92, in run
    self.create_metalinks_list()
2018-05-29 02:08:42 [ERROR] process.py(135) run():   File "/usr/share/cnchi/src/installation/process.py", line 82, in create_metalinks_list
    raise misc.InstallError(txt)
2018-05-29 02:08:42 [ERROR] process.py(135) run(): misc.extra.InstallError: 'Cannot create download package list (metalinks).
```

I have tried updating Cnchi as I read on a forum somewhere sometimes the auto-update fails, however no update is available (0.14.426). I also tried "not changing mirrorlist (default)" as suggested above with no luck. However with these error logs it would make me think the error may be in the AntergOS repos, rather than an issue with Cnchi though.

**Comment by karasu** [comment] 2018-05-29 04:58
@CorruptComputer you're right. It's not a Cnchi issue but a repo issue.

pamac needed pacman < 5.1 but pacman is now 5.1. This dependency has to be removed. Sadly, we're experiencing some issues in our build server that prevent us from rebuilding pamac.

Here is the issue you are experiencing:
https://github.com/Antergos/antergos-packages/issues/332

I'll close this one.

**Closed by karasu** 2018-05-29 04:58 UTC

**Comment by LeoTindall** [comment] 2018-07-17 21:02
I am currently having this issue, just downloaded the installer and I can't install a KDE desktop, getting this error.

**Comment by karasu** [comment] 2018-07-20 08:52
@LeoTindall yours is a duplicate of this one: https://github.com/Antergos/Cnchi/issues/913
It's already solved.

Cheers!
