### ISSUE TITLE
lsb_release missing after installation that causes other arch distributions to fail boot loader installation and hang installation for more that 30 minutes on bootloader installation step

### ISSUE THREAD

**Issue by IevgenSobko** [Antergos/Cnchi#788] opened 2017-08-23 12:30 UTC
### Problem:
lsb_release missing after installation that causes other arch distributions to fails boot loader installation
moreover bootloader installation hangs for 12 minutes on os-prober grub-mount on trying to identify os installed on Antergos volume

### Steps To Reproduce:
1. Install Antergos on /dev/sda1 with bootloader
2. Install Antergos on /dev/sda2 with bootloader
3. During second installation you will have very long installation time and bootloader will fail to install

**Comment by lots0logs** [comment] 2017-08-23 12:43
The issue is a bug in grub, specifically in grub-mount script. It is not specific to Antergos. It doesn't matter which distribution is installed on the other partitions. We implemented a workaround for the issue. It will be included the next time we bump the version on the Cnchi package in our repo.

**Closed by lots0logs** 2017-08-23 12:43 UTC
