### ISSUE TITLE
Can't install antergos : Cannot create download package list (metalinks) error: 1084614

### ISSUE THREAD

**Issue by killajoe** [Antergos/Cnchi#876] opened 2018-04-27 09:50 UTC
### Problem:
Install of all DE seems to fail with this error (different Numbers)

### Steps To Reproduce:
1. latest Antergos ISO boot up and install any DE
2. process goes true till user account screen and fails

### Log Files
cnchi.log --> https://ptpb.pw/wvxn
cnchi-alpm.log --> https://ptpb.pw/PnPE
pacman-boot.log --> https://ptpb.pw/pHyQ

### Additional Notes:
At Forum it is reported by multiple users that install fails mith metalink error!
https://forum.antergos.com/topic/9745/error-1083052-antergos-installation
https://forum.antergos.com/topic/9705/cnchi-can-t-install-necessary-packages-error-1074120
https://forum.antergos.com/topic/9721/can-t-install-error-1076268

**Comment by killajoe** [comment] 2018-04-27 12:38
https://forum.antergos.com/topic/9751/unable-to-install-cannot-create-download-package-list-metalinks

**Comment by karasu** [comment] 2018-04-28 08:25
@khbecker #865 and #875 are different errors, in fact, this #875 is a duplicate of #874 
Closing.

**Closed by karasu** 2018-04-28 08:25 UTC

**Comment by karasu** [comment] 2018-04-28 09:50
Fixed in Cnchi 0.14.425
