### ISSUE TITLE
Installer error: 'Cannot create download package list (metalinks). Check log output for details.'

### ISSUE THREAD

**Issue by polarathene** [Antergos/Cnchi#505] opened 2016-01-13 02:16 UTC
For some reason the time/date the OS had set was Jan 1 2009, I found this out by using the web browser to troubleshoot the `Cannot create download package list (metalinks). Check log output for details.` error when trying to install. The web browser would give https errors about invalid certs for any https site like google. Looked into it and it all looked good, I think there was a mention of the date, I checked what the live image had set for the date and it was something like Jan 1 2009... 

I was connected to the internet and had set the option for syncing time, it just didn't seem to be applied in the live OS, I did this and the date was fixed. Since completing the install, I've rebooted into the usb installer to verify the bug but the date was fine. Not sure what caused it, I had a corrupted windows install prior that I wiped with gparted and created a new boot esp partition, an Ubuntu install was also on the system during the install that used legacy bios to boot into rather than uefi.

I've seen others have had this problem in the past, if a check can be done on the dates year being clearly incorrect, could cnchi fix that so it can download the package list?

EDIT: Have been trying new themes out with my Antergos installation and needed to reboot a few times. When trying to access previous tabs on firefox got the same error, looked at my date and it was reset to Jan 1 2009.. Went into settings for date/time and the sync from internet options were off, I don't remember if I set them after the install but I was browsing just fine for the rest of the day so perhaps something turned them off?

**Comment by stratus-ss** [comment] 2017-01-06 19:11
@polarathene  It sounds like your bios is off. The time is first pulled from the local source (bios) and then pulled from the internet (ideally). 

As for the time issue, I believe that Antergos uses ntpd by default.

`sudo systemctl is-enabled ntpd`

will tell you whether its enabled to survive a reboot

**Comment by polarathene** [comment] 2017-01-06 21:09
I haven't installed a new OS to that system since, but after fixing the settings like mentioned it was fine. The laptop was sold in 2014, not sure if the bios would be from 2009?(especially Jan 1?)  It ran Windows 8.1 previously.

**Comment by stratus-ss** [comment] 2017-01-09 20:05
I'm closing this one due to aging and the inability to reproduce it. If you experience this again we can look at it then

**Closed by stratus-ss** 2017-01-09 20:05 UTC
