### ISSUE TITLE
Antergos fails to boot after install on certain SSD setups

### ISSUE THREAD

**Issue by aoighost** [Antergos/Cnchi#210] opened 2014-05-24 07:58 UTC
Antegros will fail to boot on some SSD and Hybrid SSD setups after install. The reason for this is documented here: https://wiki.manjaro.org/index.php?title=Kernel_Fails_to_Load_%28pata_acpi_error%29

Please integrate this fix in to the installer by default. Otherwise people with newer computers that have SSDs and Hybrid SSDs will be unable to boot in to the OS.

**Comment by sils1297** [comment] 2015-01-21 15:32
Is there a workaround? i.e. installing bootloader manually after installation.

**Comment by lots0logs** [comment] 2015-01-21 20:06
This bug was never actually confirmed in our testing. I recently tested on my brand new PC which includes an SSD/HDD setup. I had no problems.

**Comment by sils1297** [comment] 2015-01-21 20:14
I definitely reproduced what the bug title says. I cannot say anything about the exact error because I was a bit in a hurry and did a manual installation after trying three different configurations with a hybrid SSD/HDD setup which all failed. However it might also be important to note that this was an UEFI setup.

I am sorry but I can provide no more information (i.e. a log). If you have any questions where I might know the answer I'll be happy to provide them.

**Comment by karasu** [comment] 2015-01-22 11:25
Blacklisting the pata_acpi module in /etc/default/grub (as the Manjaro wiki suggests) solves your issue?

GRUB_CMDLINE_LINUX="modprobe.blacklist=pata_acpi"

**Comment by lots0logs** [comment] 2015-03-24 06:00
Closing for now. We can reopen if it comes up again.

**Closed by lots0logs** 2015-03-24 06:00 UTC
Labels: bug, needs confirmation
