### ISSUE TITLE
Slides screen increases the window height. 

### ISSUE THREAD

**Issue by lots0logs** [Antergos/Cnchi#345] opened 2015-05-20 00:29 UTC
I think this is caused by the progress bars. The documentation says that the progress text should appear within the trough. With cnchi, the text is appearing on top of the trough.

**Comment by lots0logs** [comment] 2015-05-22 21:40
After further investigation, there is no issue with the progress bars. The text is no longer displayed within the bar itself by design in 3.16.

**Comment by karasu** [comment] 2015-06-01 20:39
So we can close this or the issue is still happening? (It must be random because I do not see it here)

**Comment by lots0logs** [comment] 2015-06-02 10:36
The window height still increases by about 20px (yeah that's a guesstimate..oh and "guesstimate" is not a real word so don't bother looking it up :laughing: ) ...anyway, I think we can close this for now and revisit later if need be.

**Closed** 2015-06-02 10:36 UTC
Labels: non-critical
