### ISSUE TITLE
Antergos Installer-Error error:282858 Cannot create download package list(metalinks)

### ISSUE THREAD

**Issue by dust347** [Antergos/Cnchi#656] opened 2016-10-07 16:29 UTC
### Problem:

I'm trying to install antergos in Oracle VM VirtualBox. In the step of "Create Your User Account", a dialog appears and prompts:
Cannot create download package list(metalinks)
error:282858
### Steps To Reproduce:
1. run the cnchi.py
2. flow all steps of installation
3. at the dialog of "Create Your User Account", the error appears
### Log Files
- Link to /tmp/cnchi.log output. http://paste2.org/WEmFmn87
- Link to /tmp/postinstall.log.is empty

**Comment by stratus-ss** [comment] 2017-01-06 18:46
I haven't been able to reproduce this. @dust347 can you confirm this is still an issue for you, or has this been fixed in a recent update?

**Comment by karasu** [comment] 2017-01-07 14:06
@stratus-ss normally this happens when a package is renamed or removed. I'll close this.

**Closed by karasu** 2017-01-07 14:06 UTC

**Comment by crvs** [comment] 2017-03-18 12:37
it's happening again with the latest installer

**Comment by karasu** [comment] 2017-03-18 21:56
@crvs Do you have any logs?

**Comment by Haxk20** [comment] 2017-03-19 10:16
@karasu  the log file:
2017-03-19 10:09:18 [INFO] slides.py(268) manage_events_from_cb_queue(): Creating the list of packages to download...
2017-03-19 10:10:04 [ERROR] metalink.py(124) create(): Can't find these packages: lib32-mesa-libgl 
2017-03-19 10:10:04 [ERROR] download.py(145) create_metalinks_list(): Error creating metalink for package lib32-mesa-libgl. Installation will stop
2017-03-19 10:10:04 [ERROR] download.py(177) create_metalinks_list(): Can't create download set. An exception of type InstallError occured. Arguments:
('Error creating metalink for package lib32-mesa-libgl. Installation will stop',)
2017-03-19 10:10:04 [ERROR] process.py(128) run(): 'Cannot create download package list (metalinks).'
2017-03-19 10:10:04 [ERROR] process.py(132) run(): Traceback (most recent call last):
2017-03-19 10:10:04 [ERROR] process.py(132) run():   File "/usr/share/cnchi/cnchi/installation/process.py", line 93, in run
    self.create_metalinks_list()
2017-03-19 10:10:04 [ERROR] process.py(132) run():   File "/usr/share/cnchi/cnchi/installation/process.py", line 83, in create_metalinks_list
    raise misc.InstallError(txt)
2017-03-19 10:10:04 [ERROR] process.py(132) run(): misc.extra.InstallError: 'Cannot create download package list (metalinks).'
2017-03-19 10:10:04 [DEBUG] connectionpool.py(207) _new_conn(): Starting new HTTP connection (1): build.antergos.com
2017-03-19 10:10:05 [DEBUG] connectionpool.py(395) _make_request(): http://build.antergos.com:80 "GET /hook?cnchi=2580656b5c7be34e4144a3129a95e421&install_id=521417&result=False HTTP/1.1" 301 None
2017-03-19 10:10:05 [DEBUG] connectionpool.py(395) _make_request(): http://build.antergos.com:80 "GET /api/hook?cnchi=2580656b5c7be34e4144a3129a95e421&install_id=521417&result=False HTTP/1.1" 200 None

**Comment by Haxk20** [comment] 2017-03-19 10:17
i cannot install the system thats a big problem and needs to be fixed

**Comment by Haxk20** [comment] 2017-03-19 10:24
my solution:
sudo pacman -S cnchi
sudo pacman -S lib32-mesa-libgl
then launch cnchi again and it will continue with installation normally.

**Comment by karasu** [comment] 2017-03-19 11:27
>2017-03-19 10:10:04 [ERROR] metalink.py(124) create(): Can't find these packages: lib32-mesa-libgl

Yep, lib32-mesa-libgl got removed. That's already fixed, that's why updating Cnchi worked for you.

What I do not get is why it wasn't updating itself in the first place.

**Comment by crvs** [comment] 2017-03-19 18:33
Just seen the answer, sorry I didn't provide better feedback yesterday. I'm installing it now, it seems to be working fine
