### ISSUE TITLE
KDE Plasma crash 

### ISSUE THREAD

**Issue by rplanchuelo** [Antergos/Cnchi#984] opened 2018-08-24 10:21 UTC
**Describe the bug**
I think that Arch is removed old Plasma packages and Cnchi crash when it tries to install Plasma. Now is with breeze-kde4, but it's possible that there'll be some packages more

**To Reproduce**
1.Install Antergos with KDE Plamsa

**Log Files**
[cnchlog3.log](https://github.com/Antergos/Cnchi/files/2317966/cnchlog3.log)

**Additional context**

**Comment by avaskar** [comment] 2018-08-24 11:58
I can confirm that installing KDE is currently not working.

Yesterday, the problem was with the KDE localization packages, now Arch removed more packages like kdesudo.

So installing is currently not possible.

Log files:

[cnchi.log](https://github.com/Antergos/Cnchi/files/2318223/cnchi.log)

**Comment by karasu** [comment] 2018-09-01 18:29
Fixed in Cnchi 0.14.475
Closing.

**Closed by karasu** 2018-09-01 18:29 UTC

**Comment by rplanchuelo** [comment] 2018-09-01 19:03
Thanks a lot
