### ISSUE TITLE
error 209926

### ISSUE THREAD

**Issue by davidhijomaria** [Antergos/Cnchi#636] opened 2016-07-25 20:30 UTC
### Problem:
*No se pueden instalar los paquetes, cnchi no puede continuar.*

### Steps To Reproduce:
1.Installing Antergos on a Lenovo 
2.Using a ext4 partition for home
3.Working with Grub (no uefi).
4.The installer says: "error 209926 cnchi no puede instalar los paquetes que faltan, no puede continuar"

### Additional Notes:
This thing don't occur with other pc (hp with uefi).

Thank's

**Comment by karasu** [comment] 2016-07-25 21:57
Hi, 
Which desktop did you try? Cinnamon? And with the other pc (hp) which desktop did you install on it?

**Comment by lots0logs** [comment] 2016-07-25 22:11
@karasu https://bugsnag.com/antergos/cnchi/errors?filters[event.since][]=30d&filters[error.status][]=open&filters[user.name][]=209926

**Comment by karasu** [comment] 2016-07-25 22:26
This is new... @lots0logs , how come `grub2-theme-antergos` has a file conflict?

**Comment by lots0logs** [comment] 2016-07-25 23:35
@karasu Not sure..I didnt really look at it..just wanted you to know that we can access them that way. I will take a look when I get off work tho!

**Comment by davidhijomaria** [comment] 2016-07-26 00:20
Hi karasu!

I've installed gnome on both

**Comment by lots0logs** [comment] 2016-07-26 02:17
@davidhijomaria Do you have an existing installation of Antergos on your system? If not did you perhaps make another attempt to install after a failure without rebooting first?

**Comment by davidhijomaria** [comment] 2016-07-26 03:46
I had Antergos installed, but I tried to change some configuration and I miss the gnome environment... (removing GDM).

After that I tried to reinstal (with the lastest version [minimal, and live]).

In fact I've tried yet to reinstall without rebooting, but doesn't work. I have installed debian on other partition of my disc.

Now, I remember one thing more about that problem, in fact, the "first install" of Antergos was a easy, fast and "cutting edge", but re installation has been more difficult every time.

In other moments I solved this installing Archlinux (is difficult and tedious, and the drivers of my lenovo aren't so easy to find), or manjaro; ¡But after that the installing of antergos wasn't a problem!

It is a crazy answer, it must be a easier way to do the reinstallation of Antergos.

(note: Now I can't only reinstall gnome because I've formated the Antergos partition).
Thank's. David.

**Comment by karasu** [comment] 2016-07-26 10:05
Hi,

>I had Antergos installed, but when I tried to change some configuration and I lost the gnome environment... (removing GDM).

Then it was not necessary to reinstall! Next time ask for help instead of reinstalling... this way you'll learn how to fix things.

OK, please, start your computer with the live iso, wait for Cnchi to appear and update itself. Try the installation and post here the error code like you did in the first post if it fails again.

**Comment by davidhijomaria** [comment] 2016-07-27 00:55
ok

**Comment by davidhijomaria** [comment] 2016-07-27 01:53
**Antergos Installer-Error **

"no se pueden instalar los paquetes necesarios. Cnchi no puede continuar."

Error: 211113

**Comment by lots0logs** [comment] 2016-07-30 01:47
Duplicate of #633

**Closed by lots0logs** 2016-07-30 01:47 UTC
Labels: duplicate
